### ISSUE TITLE
Link to YOLO's weights file fine tuned with ICDAR19

### ISSUE THREAD

**Issue by cooleel** [holms-ur/fine-tuning#1]
Thanks for the project and open sourcing all models, this is extremely helpful. 

The Link to YOLO's weights file fine tuned with ICDAR19 seems not working right now. 
Could you please fix it. Thanks.

**Comment by joheras** [comment]
Thanks for letting us know that YOLO's weight for the ICDAR19 dataset were
not available. There are so many weights that I guess that I forgot to
include it.

The weights are available know.

Let us know if you need further help with the project.

Best,
Jónathan

**Comment by cooleel** [comment]
yeah, it's working now. thanks.
