### ISSUE TITLE
Pre-train Weights for TableBank

### ISSUE THREAD

**Issue by mehtadi** [holms-ur/fine-tuning#14]
Hi, Thank you so much for taking the time to share this. Starred.

I saw that you shared fine tuned models.
Is it possible for you to share the pre-train (non-fine tuned) weights for TableBank? I'm particularly interested in YOLO, Retina and RCNN

**Comment by joheras** [comment]
Hi,

You already have the weights for TableBank in the [fine-tuning page](https://github.com/holms-ur/fine-tuning/blob/master/FineTuning.md).

From that page, you can access to the weights for the different networks in the sections "Necessary files".

Let me know if you need further help.

**Comment by joheras** [comment]
You are right. It is better to have them in the model zoo page. I have included them there. 
Thanks.
