### ISSUE TITLE
No build_dataset.py file

### ISSUE THREAD

**Issue by PavelKovalets** [holms-ur/fine-tuning#7]
Hi!

I'm trying to follow [fine-tuning guide](https://github.com/holms-ur/fine-tuning/blob/1b1af5e0100bb1b42f734d3a5b52ae34d1ebb353/fine-tuning/retinanet.md), however I cannot execute command

     python build_dataset.py -b mydaset

because there is no such file

**Comment by joheras** [comment]
Thanks for the report. I have fixed the link to access to that file.
Sorry for the inconvenience,
Jónathan
